version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - no milestone
    commit-message:
      prefix: ci
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
