# Based on pydata/xarray
codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        # Require 1% coverage, i.e., always succeed
        target: 1
    patch: false
    changes: false

comment: off