repos:
- repo: https://github.com/flying-sheep/bibfmt
  rev: v4.3.0
  hooks:
  - id: bibfmt
    args:
    - --sort-by-bibkey
    - --drop=abstract
    groups: [format]
- repo: https://github.com/biomejs/pre-commit
  rev: v2.5.6
  hooks:
  - id: biome-format
    groups: [format]
    exclude: ^\.cruft\.json$ # inconsistent indentation with cruft - file never to be modified manually.
- repo: https://github.com/tox-dev/pyproject-fmt
  rev: v2.27.0
  hooks:
  - id: pyproject-fmt
    groups: [format]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.16.1
  hooks:
  - id: ruff-check
    args: [--fix, --exit-non-zero-on-fix]
  - id: ruff-format
    groups: [format]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: detect-private-key
  - id: check-ast
  - id: check-added-large-files
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
    groups: [format]
    exclude: tests/_data
  - id: mixed-line-ending
    groups: [format]
    args: [--fix=lf]
  - id: trailing-whitespace
    groups: [format]
    exclude: tests/_data
  - id: check-case-conflict
  # Check that there are no merge conflicts (could be generated by template sync)
  - id: check-merge-conflict
    args: [--assume-in-merge]
  - id: no-commit-to-branch
    args: [--branch=main]
- repo: https://github.com/zizmorcore/zizmor-pre-commit
  rev: v1.29.0
  hooks:
  - id: zizmor
    args: [--no-progress, --fix]
