version: 2
build:
  os: ubuntu-20.04
  tools:
    python: '3.11'
sphinx:
  fail_on_warning: true # do not change or you will be fired
  configuration: docs/conf.py
python:
  install:
  - method: pip
    path: .
    extra_requirements:
    - doc
    - leiden
