# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
submodules:
  include: all
build:
  os: ubuntu-24.04
  tools:
    python: '3.13'
  jobs:
    post_checkout:
      # unshallow so version can be derived from tag
      - git fetch --unshallow || true
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    pre_build:
      # run towncrier to preview the next version’s release notes
      - ( find docs/release-notes -regex '[^.]+[.][^.]+.md' | grep -q . ) && uvx hatch run towncrier build --keep || true
    build:
      html:
        - uvx hatch run docs:build
        - mv docs/_build $READTHEDOCS_OUTPUT
