name: Bug report
description: Scanpy doesn’t do what it should? Please help us fix it!
title: ''
labels: [bug]
assignees: ''
body:
- type: checkboxes
  id: terms
  attributes:
    # label: ...
    # description: ...
    options:
    - label: I have checked that this issue has not already been reported.
      required: true
    - label: I have confirmed this bug exists on the latest version of scanpy.
      required: true
    - label: (optional) I have confirmed this bug exists on the master branch of scanpy.
      required: false
- type: markdown
  attributes:
    value: |
      **Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.
- type: textarea
  id: code
  attributes:
    label: Minimal code sample
    description: (that we can copy&paste without having any data)
    render: python
  validations:
    required: true
- type: textarea
  id: tb
  attributes:
    label: Error output
    description: (produced by the code above)
    render: pytb
  validations:
    required: true
- type: textarea
  id: tb
  attributes:
    label: Versions
    description: Paste the output of scanpy.logging.print_versions() leaving a blank line after the details tag
    render: markdown
    placeholder: |
      <details>



      </details>
  validations:
    required: true
