blank_issues_enabled: true
contact_links:
  - name: Scanpy Community Forum
    url: https://discourse.scverse.org/
    about: If you have questions about “How to do X”, please ask them here.
  - name: Blank issue
    url: https://github.com/scverse/scanpy/issues/new
    about: For things that don't quite fit elsewhere. Please note that other templates should be used in most cases – this is mainly for use by the developers.
