name: autofix.ci

on:
  push:
    branches:
      - main
      - "[0-9]+.[0-9]+.x"
  pull_request:

env:
  PYTEST_ADDOPTS: "-v --color=yes -n auto --internet-tests --junitxml=test-data/test-results.xml"
  FORCE_COLOR: "1"
  MPLBACKEND: agg
  # It’s impossible to ignore SyntaxWarnings for a single module,
  # so because leidenalg 0.10.0 has them, we pre-compile things: https://github.com/vtraag/leidenalg/issues/173
  UV_COMPILE_BYTECODE: "1"

permissions:
  contents: read

jobs:
  get-environments:
    runs-on: ubuntu-latest
    outputs:
      envs: ${{ steps.get-envs.outputs.envs }}
    steps:
      - &clone
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          filter: blob:none
          persist-credentials: false
      - &setup-uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          enable-cache: true
      - id: get-envs
        run: |
          ENVS_JSON=$(NO_COLOR=1 uvx hatch env show --json | jq -c 'to_entries
            | map(
              select(.key | startswith("hatch-test"))
              | {
                name: .key,
                "test-type": (if (.key | test("pre|low-vers")) then "coverage" else null end),
                python: .value.python
              }
            )')
          echo "envs=${ENVS_JSON}" | tee $GITHUB_OUTPUT

  test:
    needs: get-environments
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ${{ fromJSON(needs.get-environments.outputs.envs) }}
    permissions:
      id-token: write  # for codecov OIDC
    env:
      UV_PYTHON: ${{ matrix.env.python }}
    steps:
      - *clone
      - *setup-uv
      - name: Cache downloaded data
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: .pytest_cache/d/scanpy-data
          key: pytest

      - name: Install dependencies
        run: |
          echo "::group::Install hatch"
          uv tool install hatch
          echo "::endgroup::"
          echo "::group::Create environment"
          hatch -v env create ${{ matrix.env.name }}
          echo "::endgroup::"
          hatch run ${{ matrix.env.name }}:session-info scanpy anndata

      - name: Run tests
        if: matrix.env.test-type == null
        run: hatch run ${{ matrix.env.name }}:run
      - name: Run tests (coverage)
        if: matrix.env.test-type == 'coverage'
        run: |
          hatch run ${{ matrix.env.name }}:run-cov
          hatch run ${{ matrix.env.name }}:cov-combine
          hatch run ${{ matrix.env.name }}:coverage xml
          hatch run ${{ matrix.env.name }}:cov-report

      - name: Upload coverage data
        if: ${{ !cancelled() && matrix.env.test-type == 'coverage' }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          flags: ${{ matrix.env.name }}
          files: test-data/coverage.xml
          use_oidc: true
          fail_ci_if_error: true

      - name: Upload test results
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          report_type: test_results
          flags: ${{ matrix.env.name }}
          files: test-data/test-results.xml
          use_oidc: true
          fail_ci_if_error: true

      - name: Publish debug artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: debug-data-${{ matrix.env.name }}
          path: .pytest_cache/d/debug

  build:
    runs-on: ubuntu-latest
    steps:
      - *clone
      - *setup-uv
      - run: uvx --from build pyproject-build --sdist --wheel .
      - run: uvx twine check dist/*

  lint:
    name: Pre-commit checks
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - *clone
      - *setup-uv
      - run: uv tool install hatch
      - name: Run pre-commit hooks
        run: uvx prek run --all-files --show-diff-on-failure --color=always
        env:
          SKIP: no-commit-to-branch
      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1.3.4
        if: ${{ !cancelled() }}

  check:
    if: always()
    needs:
      - get-environments
      - test
      - build
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@b5b5b37504aa4183270bd3d855c52a67f212be35 # v1.3.0
        with:
          jobs: ${{ toJSON(needs) }}
